### ISSUE TITLE
submitting score not working

### ISSUE THREAD

**Issue by ThePooN** [Itsyuka/KaiBancho#17]
Submitting a score give me that error:
local.ERROR: exception 'ErrorException' with message 'Undefined offset: 13' in /app/Http/Controllers/Ranking.php:85

**Comment by Itsyuka** [comment]
`Log::Info($score);`

If that doesn't show when submitting, then there was an issue somewhere.

**Comment by ThePooN** [comment]
Uh, I got that error when I was on cutting-edge, so yeah it's fixed i guess.
