### ISSUE TITLE
How to connect?

### ISSUE THREAD

**Issue by LossFirst** [Itsyuka/KaiBancho#23]
How to connect?
I will not be able to connect to the KaiBancho.

**Comment by Jan4V** [comment]
Modify OsuPatcher to your servers ip address, put a compiled version into your osu! directory, run it, and use the patched version of osu!.

**Comment by centurioncenturion** [comment]
or modify your hosts file

**Comment by LossFirst** [comment]
>>Modify OsuPatcher to your servers ip address, put a compiled version into your osu! directory, run it, and use the patched version of osu!.

I did it
But I can't connect.
http://prntscr.com/ad22ka
http://prntscr.com/ad22zw

**Comment by Itsyuka** [comment]
You've created an SSL cert and installed it in your PC?

**Comment by Itsyuka** [comment]
And server

**Comment by Itsyuka** [comment]
Closing because no response.
