### ISSUE TITLE
Find and document all osu packet send/receive

### ISSUE THREAD

**Issue by Itsyuka** [Itsyuka/KaiBancho#8]
This would be super beneficial to continue working with new functions.

**Comment by Itsyuka** [comment]
https://github.com/Itsyuka/KaiBanchoo-Web/wiki/Packets

**Comment by Igoorx** [comment]
A little of received packets to try to help you:
0 is to update the status of the local player
16 is to inform the target player that has a spectator_ thus enabling it to send their play to Bancho_
17 is to stop spectating the spectated player
18 is received with the play of local player and repassed to players that are spectating it
30 is to inform the bancho when player enter the multiplayer and 29 is when exit _i guess_
32 is to go into a lobby and 33 is to leave the current lobby/match
87 is to invite a player to a lobby

**Comment by Itsyuka** [comment]
29 can be called when getting into the room listings, and is also called when it exists an actual room to update.

Updated the wiki page.

**Comment by Itsyuka** [comment]
https://github.com/Itsyuka/KaiBancho/blob/0fcfd3034568a1a1b5574fbdb8465c047272e0f5/app/Libraries/Packets.php
